"""added helpful

Revision ID: 477266f2ac1a
Revises: 01083861e26d
Create Date: 2023-05-01 09:26:25.486727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477266f2ac1a'
down_revision = '01083861e26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpful', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('helpful')

    # ### end Alembic commands ###
