"""redo help/funny

Revision ID: b31fd60b222c
Revises: 70d7807ef3b4
Create Date: 2023-05-05 12:10:42.651066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31fd60b222c'
down_revision = '70d7807ef3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('helpful',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('funny',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('funny',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('helpful',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
