"""added helpful

Revision ID: c15ba8900e73
Revises: 477266f2ac1a
Create Date: 2023-05-01 10:39:45.930127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15ba8900e73'
down_revision = '477266f2ac1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('helpful')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpful', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
