"""added pw

Revision ID: e517281afa60
Revises: d623773c48ac
Create Date: 2023-05-02 15:11:49.932515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e517281afa60'
down_revision = 'd623773c48ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salons', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
